# See https://docs.codecov.io/docs/commit-status
coverage:
  parsers:
    javascript:
      enable_partials: yes
  status:
    project:
      default:
        # TODO: re-enable this when we start having better coverage
        # target: 90%
        informational: true # do not fail build if coverage level is not met
    patch: off

# See https://docs.codecov.io/docs/pull-request-comments
comment:
  layout: 'diff, flags, files' # hide the Reach graph
  require_changes: true # only post comment to PR if coverage changes

ignore:
  - packages/*/_package.config.js
  - packages/*/studio.config.js
  - packages/*/jest.config.js
  - packages/*/webpack.config.js
