compressionLevel: mixed

enableGlobalCache: true

nodeLinker: node-modules

npmPublishAccess: public

packageExtensions:
  postcss-loader@*:
    peerDependenciesMeta:
      "@types/node":
        optional: true
  react-measure@*:
    peerDependenciesMeta:
      react-dom:
        optional: true
  zipkin-transport-http@*:
    peerDependenciesMeta:
      node-fetch:
        optional: true

yarnPath: .yarn/releases/yarn-4.5.1.cjs
