enableGlobalCache: true

nodeLinker: node-modules

npmPublishAccess: public

packageExtensions:
  postcss-loader@*:
    peerDependenciesMeta:
      '@types/node':
        optional: true
  react-measure@*:
    peerDependenciesMeta:
      react-dom:
        optional: true
  zipkin-transport-http@*:
    peerDependenciesMeta:
      node-fetch:
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: '@yarnpkg/plugin-constraints'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.6.1.cjs
