constraintsPath: .yarn/constraints.pro

enableGlobalCache: true

nodeLinker: node-modules

npmPublishAccess: public

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: '@yarnpkg/plugin-constraints'

yarnPath: .yarn/releases/yarn-2.4.1.cjs

packageExtensions:
  react-measure@*:
    peerDependenciesMeta:
      react-dom:
        optional: true
  zipkin-transport-http@*:
    peerDependenciesMeta:
      node-fetch:
        optional: true
