/**
 * Copyright (c) 2026-present, Goldman Sachs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Generated by the engine (grammar to JSON), then trimmed to match the
 * graph transformer's output: `sourceInformation` and the empty
 * `includedStores`, `stereotypes`, `tabularFunctions` and `milestoning`
 * arrays are removed. The source grammar:
 *
 * ```
 * ###Relational
 * Database test::dbInc
 * (
 *   Table INC_T
 *   (
 *     ID INTEGER PRIMARY KEY,
 *     CODE CHAR(3) NOT NULL
 *   )
 * )
 *
 * ###Relational
 * Database test::db
 * (
 *   include test::dbInc
 *
 *   Schema s1
 *   (
 *     View EARLY_CROSS_SCHEMA
 *     (
 *       ID: s2.LATE_V.ID PRIMARY KEY
 *     )
 *   )
 *   Schema s2
 *   (
 *     Table T2
 *     (
 *       ID INTEGER PRIMARY KEY
 *     )
 *     View LATE_V
 *     (
 *       ID: s2.T2.ID PRIMARY KEY
 *     )
 *   )
 *
 *   Table T
 *   (
 *     ID INTEGER PRIMARY KEY,
 *     AMT DECIMAL(10,2),
 *     NAME VARCHAR(20),
 *     OTHER_ID INTEGER NOT NULL
 *   )
 *   Table OTHER
 *   (
 *     ID INTEGER PRIMARY KEY,
 *     TS TIMESTAMP NOT NULL
 *   )
 *   View V_OVER_V_FORWARD
 *   (
 *     ID: V.ID PRIMARY KEY,
 *     AMT: V.AMT,
 *     UPPER_NAME: V.UPPER_NAME
 *   )
 *   View V
 *   (
 *     ID: T.ID PRIMARY KEY,
 *     AMT: T.AMT,
 *     NAME: T.NAME,
 *     UPPER_NAME: toUpper(T.NAME),
 *     OTHER_TS: @T_OTHER | OTHER.TS
 *   )
 *   View V_OVER_V_BACKWARD
 *   (
 *     ID: V.ID PRIMARY KEY,
 *     AMT: V.AMT,
 *     NAME: V.NAME,
 *     UPPER_NAME: V.UPPER_NAME,
 *     OTHER_TS: V.OTHER_TS
 *   )
 *   View V_INC
 *   (
 *     ID: INC_T.ID PRIMARY KEY,
 *     CODE: INC_T.CODE
 *   )
 *
 *   Join T_OTHER(T.OTHER_ID = OTHER.ID)
 * )
 * ```
 */
export const TEST_DATA__ViewColumnTypes = [
  {
    path: 'test::dbInc',
    content: {
      _type: 'relational',
      filters: [],
      joins: [],
      name: 'dbInc',
      package: 'test',
      schemas: [
        {
          name: 'default',
          tables: [
            {
              columns: [
                {
                  name: 'ID',
                  nullable: false,
                  type: {
                    _type: 'Integer',
                  },
                },
                {
                  name: 'CODE',
                  nullable: false,
                  type: {
                    _type: 'Char',
                    size: 3,
                  },
                },
              ],
              name: 'INC_T',
              primaryKey: ['ID'],
            },
          ],
          views: [],
        },
      ],
    },
    classifierPath: 'meta::relational::metamodel::Database',
  },
  {
    path: 'test::db',
    content: {
      _type: 'relational',
      filters: [],
      includedStores: [
        {
          path: 'test::dbInc',
          type: 'STORE',
        },
      ],
      joins: [
        {
          name: 'T_OTHER',
          operation: {
            _type: 'dynaFunc',
            funcName: 'equal',
            parameters: [
              {
                _type: 'column',
                column: 'OTHER_ID',
                table: {
                  _type: 'Table',
                  database: 'test::db',
                  mainTableDb: 'test::db',
                  schema: 'default',
                  table: 'T',
                },
                tableAlias: 'T',
              },
              {
                _type: 'column',
                column: 'ID',
                table: {
                  _type: 'Table',
                  database: 'test::db',
                  mainTableDb: 'test::db',
                  schema: 'default',
                  table: 'OTHER',
                },
                tableAlias: 'OTHER',
              },
            ],
          },
        },
      ],
      name: 'db',
      package: 'test',
      schemas: [
        {
          name: 's1',
          tables: [],
          views: [
            {
              columnMappings: [
                {
                  name: 'ID',
                  operation: {
                    _type: 'column',
                    column: 'ID',
                    table: {
                      _type: 'Table',
                      database: 'test::db',
                      mainTableDb: 'test::db',
                      schema: 's2',
                      table: 'LATE_V',
                    },
                    tableAlias: 'LATE_V',
                  },
                },
              ],
              distinct: false,
              groupBy: [],
              name: 'EARLY_CROSS_SCHEMA',
              primaryKey: ['ID'],
            },
          ],
        },
        {
          name: 's2',
          tables: [
            {
              columns: [
                {
                  name: 'ID',
                  nullable: false,
                  type: {
                    _type: 'Integer',
                  },
                },
              ],
              name: 'T2',
              primaryKey: ['ID'],
            },
          ],
          views: [
            {
              columnMappings: [
                {
                  name: 'ID',
                  operation: {
                    _type: 'column',
                    column: 'ID',
                    table: {
                      _type: 'Table',
                      database: 'test::db',
                      mainTableDb: 'test::db',
                      schema: 's2',
                      table: 'T2',
                    },
                    tableAlias: 'T2',
                  },
                },
              ],
              distinct: false,
              groupBy: [],
              name: 'LATE_V',
              primaryKey: ['ID'],
            },
          ],
        },
        {
          name: 'default',
          tables: [
            {
              columns: [
                {
                  name: 'ID',
                  nullable: false,
                  type: {
                    _type: 'Integer',
                  },
                },
                {
                  name: 'AMT',
                  nullable: true,
                  type: {
                    _type: 'Decimal',
                    precision: 10,
                    scale: 2,
                  },
                },
                {
                  name: 'NAME',
                  nullable: true,
                  type: {
                    _type: 'Varchar',
                    size: 20,
                  },
                },
                {
                  name: 'OTHER_ID',
                  nullable: false,
                  type: {
                    _type: 'Integer',
                  },
                },
              ],
              name: 'T',
              primaryKey: ['ID'],
            },
            {
              columns: [
                {
                  name: 'ID',
                  nullable: false,
                  type: {
                    _type: 'Integer',
                  },
                },
                {
                  name: 'TS',
                  nullable: false,
                  type: {
                    _type: 'Timestamp',
                  },
                },
              ],
              name: 'OTHER',
              primaryKey: ['ID'],
            },
          ],
          views: [
            {
              columnMappings: [
                {
                  name: 'ID',
                  operation: {
                    _type: 'column',
                    column: 'ID',
                    table: {
                      _type: 'Table',
                      database: 'test::db',
                      mainTableDb: 'test::db',
                      schema: 'default',
                      table: 'V',
                    },
                    tableAlias: 'V',
                  },
                },
                {
                  name: 'AMT',
                  operation: {
                    _type: 'column',
                    column: 'AMT',
                    table: {
                      _type: 'Table',
                      database: 'test::db',
                      mainTableDb: 'test::db',
                      schema: 'default',
                      table: 'V',
                    },
                    tableAlias: 'V',
                  },
                },
                {
                  name: 'UPPER_NAME',
                  operation: {
                    _type: 'column',
                    column: 'UPPER_NAME',
                    table: {
                      _type: 'Table',
                      database: 'test::db',
                      mainTableDb: 'test::db',
                      schema: 'default',
                      table: 'V',
                    },
                    tableAlias: 'V',
                  },
                },
              ],
              distinct: false,
              groupBy: [],
              name: 'V_OVER_V_FORWARD',
              primaryKey: ['ID'],
            },
            {
              columnMappings: [
                {
                  name: 'ID',
                  operation: {
                    _type: 'column',
                    column: 'ID',
                    table: {
                      _type: 'Table',
                      database: 'test::db',
                      mainTableDb: 'test::db',
                      schema: 'default',
                      table: 'T',
                    },
                    tableAlias: 'T',
                  },
                },
                {
                  name: 'AMT',
                  operation: {
                    _type: 'column',
                    column: 'AMT',
                    table: {
                      _type: 'Table',
                      database: 'test::db',
                      mainTableDb: 'test::db',
                      schema: 'default',
                      table: 'T',
                    },
                    tableAlias: 'T',
                  },
                },
                {
                  name: 'NAME',
                  operation: {
                    _type: 'column',
                    column: 'NAME',
                    table: {
                      _type: 'Table',
                      database: 'test::db',
                      mainTableDb: 'test::db',
                      schema: 'default',
                      table: 'T',
                    },
                    tableAlias: 'T',
                  },
                },
                {
                  name: 'UPPER_NAME',
                  operation: {
                    _type: 'dynaFunc',
                    funcName: 'toUpper',
                    parameters: [
                      {
                        _type: 'column',
                        column: 'NAME',
                        table: {
                          _type: 'Table',
                          database: 'test::db',
                          mainTableDb: 'test::db',
                          schema: 'default',
                          table: 'T',
                        },
                        tableAlias: 'T',
                      },
                    ],
                  },
                },
                {
                  name: 'OTHER_TS',
                  operation: {
                    _type: 'elemtWithJoins',
                    joins: [
                      {
                        db: 'test::db',
                        name: 'T_OTHER',
                      },
                    ],
                    relationalElement: {
                      _type: 'column',
                      column: 'TS',
                      table: {
                        _type: 'Table',
                        database: 'test::db',
                        mainTableDb: 'test::db',
                        schema: 'default',
                        table: 'OTHER',
                      },
                      tableAlias: 'OTHER',
                    },
                  },
                },
              ],
              distinct: false,
              groupBy: [],
              name: 'V',
              primaryKey: ['ID'],
            },
            {
              columnMappings: [
                {
                  name: 'ID',
                  operation: {
                    _type: 'column',
                    column: 'ID',
                    table: {
                      _type: 'Table',
                      database: 'test::db',
                      mainTableDb: 'test::db',
                      schema: 'default',
                      table: 'V',
                    },
                    tableAlias: 'V',
                  },
                },
                {
                  name: 'AMT',
                  operation: {
                    _type: 'column',
                    column: 'AMT',
                    table: {
                      _type: 'Table',
                      database: 'test::db',
                      mainTableDb: 'test::db',
                      schema: 'default',
                      table: 'V',
                    },
                    tableAlias: 'V',
                  },
                },
                {
                  name: 'NAME',
                  operation: {
                    _type: 'column',
                    column: 'NAME',
                    table: {
                      _type: 'Table',
                      database: 'test::db',
                      mainTableDb: 'test::db',
                      schema: 'default',
                      table: 'V',
                    },
                    tableAlias: 'V',
                  },
                },
                {
                  name: 'UPPER_NAME',
                  operation: {
                    _type: 'column',
                    column: 'UPPER_NAME',
                    table: {
                      _type: 'Table',
                      database: 'test::db',
                      mainTableDb: 'test::db',
                      schema: 'default',
                      table: 'V',
                    },
                    tableAlias: 'V',
                  },
                },
                {
                  name: 'OTHER_TS',
                  operation: {
                    _type: 'column',
                    column: 'OTHER_TS',
                    table: {
                      _type: 'Table',
                      database: 'test::db',
                      mainTableDb: 'test::db',
                      schema: 'default',
                      table: 'V',
                    },
                    tableAlias: 'V',
                  },
                },
              ],
              distinct: false,
              groupBy: [],
              name: 'V_OVER_V_BACKWARD',
              primaryKey: ['ID'],
            },
            {
              columnMappings: [
                {
                  name: 'ID',
                  operation: {
                    _type: 'column',
                    column: 'ID',
                    table: {
                      _type: 'Table',
                      database: 'test::db',
                      mainTableDb: 'test::db',
                      schema: 'default',
                      table: 'INC_T',
                    },
                    tableAlias: 'INC_T',
                  },
                },
                {
                  name: 'CODE',
                  operation: {
                    _type: 'column',
                    column: 'CODE',
                    table: {
                      _type: 'Table',
                      database: 'test::db',
                      mainTableDb: 'test::db',
                      schema: 'default',
                      table: 'INC_T',
                    },
                    tableAlias: 'INC_T',
                  },
                },
              ],
              distinct: false,
              groupBy: [],
              name: 'V_INC',
              primaryKey: ['ID'],
            },
          ],
        },
      ],
    },
    classifierPath: 'meta::relational::metamodel::Database',
  },
];
