export enum PERSISTENCE_HASH_STRUCTURE {
  PERSISTENCE_PIPE = 'PERSISTENCE_PIPE',
  OPAQUE_TRIGGER = 'OPAQUE_TRIGGER',
  SERVICE_READER = 'SERVICE_READER',
  STREAMING_PERSISTER = 'STREAMING_PERSISTER',
  BATCH_PERSISTER = 'BATCH_PERSISTER',
  TARGET_SPECIFICATION = 'TARGET_SPECIFICATION',
  GROUPED_FLAT_TARGET_SPECIFICATION = 'GROUPED_FLAT_TARGET_SPECIFICATION',
  FLAT_TARGET_SPECIFICATION = 'FLAT_TARGET_SPECIFICATION',
  NESTED_TARGET_SPECIFICATION = 'NESTED_TARGET_SPECIFICATION',
  PROPERTY_AND_FLAT_TARGET_SPECIFICATION = 'PROPERTY_AND_FLAT_TARGET_SPECIFICATION',
}
