blank_issues_enabled: false
contact_links:
  # - name: 🗣 Ask a Question, Discuss
  #   url: https://github.com/.../discussions
  #   about: How does X work 🤔? I made this! I have an idea..
  # - name: 💡 Propose an RFC
  #   url: https://github.com/.../rfcs
  #   about: To suggest a new option or substantial change.
