blank_issues_enabled: false
contact_links:
  - name: 📃 Documentation Issue
    url: https://github.com/finos/legend/issues/new/choose
    about: This issue tracker is not for documentation issues. Please file documentation issues here.
  - name: 🤔 Questions and Help
    url: https://github.com/finos/legend/issues/new/choose
    about: This issue tracker is not for support questions. Please ask questions and seek for help here.
