name: '🗓️ Iteration Planning'
description: 'To chart out and summarize planning for future iterations'
title: 'Iteration Plan for Version <version>.0.0 (<month> - e.g. Feb 2022)'
labels: ['Type: Planning']
body:
  - type: markdown
    attributes:
      value: |
        **⚠️ Note:** Please note that this meant only for core team to be used for planning.
        This will serve as a summary/overview of the iteration and the milestone being worked on, which will give users and developers a quicker and more organized view of the state of development compared to what the milestone issues page offers.
  - type: textarea
    attributes:
      label: Overview
      description: |
        A concise description of what the work in the iteration will be about. Please use this to highlight new features and notable bug fixes.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Plan
      description: |
        Details about tasks (with hyperlink to their issues and PRs). Please group these by our convention to make it organized and easy to explore.
    validations:
      required: true
