name: '💡 Propose an RFC'
description: 'To suggest a refactor or a functionality with substantial change'
title: 'RFC: <title>'
labels: ['Type: Discussion']
body:
  - type: textarea
    attributes:
      label: Overview
      description: |
        A concise description of what this RFC is trying to achieve: the improvements, the problems it tries to solve, etc.

        **⚠️ Note:** Please don't abuse RFCs for requesting new features or feature improvements. RFCs are strictly meant for works that require **substantial** changes to the code base, such as refactoring, or introducing new extensions and DSLs, etc. As such, use this RFC to communicate your idea, to gather feedback on your plan through discussions, so as to hone the it into a good design documentation.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Implementation plan
      description: |
        A detailed description of the solution in terms of user interface, workflow, and code logic.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Any other things you have considered: alternatives, testing strategy, migration plan, etc.
