name: (Manual) Docker Publish

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag (e.g. 1.7.0-rc.1, 0.0.1-beta)'
        required: true
        default: 'snapshot'

jobs:
  manual-publish-docker-image:
    # There is currently no way to limit workflow dispatch to only allow default branch
    # so we need to restrict it here
    # See https://github.community/t/limit-branch-for-workflow-dispatch/122099
    if: github.ref == 'refs/heads/master' && github.repository == 'finos/legend-studio'
    name: Publish Docker Image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: finos/legend-studio
            package: '@finos/legend-studio-deployment'
          - image: finos/legend-query
            package: '@finos/legend-query-deployment'
          - image: finos/legend-taxonomy
            package: '@finos/legend-taxonomy-deployment'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0
      - name: Get Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - name: Setup Yarn cache
        uses: actions/cache@v2.1.7
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Setup Node
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 14.x
      - name: Install dependencies
        run: yarn
      - name: Check Docker image tag
        run: node ./scripts/docker/checkDockerImageTag.js ${{ github.event.inputs.tag }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: finos
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish to Docker
        run: yarn build && yarn workspace ${{ matrix.package }} publish:docker ${{ github.event.inputs.tag }}
        env:
          # TODO: After https://github.com/finos/legend-studio/pull/227 it seems like due to either
          # the upgrade of Webpack/Typescript that we start seeing some OOM when building Webpack
          # while publishing to Docker. We should once in a while remove this line and try again.
          NODE_OPTIONS: '--max_old_space_size=4096'
