name: Manual Tests

on:
  schedule:
    - cron: '0 0 * * *' # runs every day on default/base branch
  push:
    branches:
      - master
      - 'release/**'
  pull_request:
    branches:
      - '**'

jobs:
  # This job will run the grammar roundtrip test suite in Studio, which requires engine
  # backend for the grammar parser/composer.
  #
  # NOTE: as we want to make sure Studio integrates well with engine, we will use the latest
  # code on `finos/legend-engine` default branch.
  # This requires us to build engine though, which might take a bit of time.
  #
  # The faster alternative is to use a fixed version, or to use the snapshot build of engine
  # on either Maven Central or Docker Hub-right now, this is not possible because we don't
  # publish the latest snapshot to these registries. So if we need to go this route, we would
  # need to use the latest published version instead.
  run-manual-tests:
    name: Run Engine Roundtrip Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0
      - name: Checkout engine server code
        uses: actions/checkout@v2.4.0
        with:
          repository: finos/legend-engine
          path: legend-engine
      - name: Setup Maven cache
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
      - name: Get Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - name: Setup Yarn cache
        uses: actions/cache@v2.1.6
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Setup Node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 14.x
      # Build the engine server and run it in the background
      - name: Run engine server
        run: |
          cd legend-engine
          mvn de.qaware.maven:go-offline-maven-plugin:resolve-dependencies
          mvn -pl legend-engine-server -am -DskipTests clean install
          java -cp legend-engine-server/target/*-shaded.jar org.finos.legend.engine.server.Server server ../packages/legend-manual-tests/engine-config.json &
      - name: Test
        # TODO: we should consider building only relevant workspaces to reduce build time
        run: yarn && yarn build && yarn workspace @finos/legend-manual-tests test:manual
