name: Release Docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - name: Setup Yarn cache
        uses: actions/cache@v2.1.4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Setup Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x
      - name: Install dependencies
        run: yarn
      - name: Build application
        run: yarn build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.TEMP_DOCKERHUB_USERNAME }} # TODO: change this when we're ready to do real release
          password: ${{ secrets.TEMP_DOCKERHUB_TOKEN }} # TODO: change this when we're ready to do real release
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        working-directory: ./packages/legend-studio-app
        with:
          push: true
          tags: blacksteed232/legend-studio:${{ date +%Y%m%d }}
      - name: Docker image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
