name: Release Docker

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    if: "github.event.head_commit.message == 'chore: bump versions and release'"
    runs-on: ubuntu-latest
    steps:
      # TODO: to remove this once we verify we can rely on github.event.head_commit.message
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - name: Setup Yarn cache
        uses: actions/cache@v2.1.4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Setup Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x
      - name: Install dependencies
        run: yarn
      - name: Build application
        run: yarn build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          # Re-enable this when we're ready
          # username: ${{ secrets.DOCKER_USERNAME }}
          # password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Generate Docker image tag
        id: generate-docker-image-tag
        run: echo "::set-output name=tag::$(date +%Y%m%d)"
      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./packages/legend-studio-app
          file: ./packages/legend-studio-app/Dockerfile
          tags: finos/legend-studio:${{ steps.generate-docker-image-tag.outputs.tag }}
      - name: Docker image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
