name: __TEST__

on:
  pull_request:
    branches:
      - '**'

jobs:
  test-publish:
    name: __TEST__ publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Get Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - name: Setup Yarn cache
        uses: actions/cache@v2.1.6
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Setup Node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 14.x
      - name: Install dependencies
        run: yarn
      - name: Build setup
        run: yarn build:setup
      - name: Test publish
        run: >
          yarn workspace @finos/legend-studio-app publish:docker &&
          yarn workspace @finos/legend-query-app publish:docker
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
